FROM postgis/postgis:16-3.4

RUN apt-get update && apt-get install -y \
    postgresql-16-pgvector \
    && rm -rf /var/lib/apt/lists/*

RUN echo "shared_preload_libraries='vector'" >> /usr/share/postgresql/postgresql.conf.sample
